### PR TITLE
Server should behave more like original.

### PR DESCRIPTION
**Pull request by krzycho1024**

### CODE REVIEW

**Comment by krzycho1024** [comment]
What's wrong with my fix?

**Comment by krzycho1024** [comment]
http://krzycho.wapp.pl/agar.png
http://krzycho.wapp.pl/agar2.png

I eaten all players, then ejected as much mass as possible, then recombined to 1 cell(~14k mass) and eaten that ejected mass. It's impossible to eat viruses and mass and be that big- only way is to eject mass and then eat it. When I reached max mass cells just split into two(wasn't expecting that). I made this screens to show my friends how big I where(someone at work told me he had 18k mass, so I had to beat that). Hope this proof is enough for you- it would be really hard to do again it.

**Comment by Ephemerality** [comment]
Hm, interesting. And this was on an official server FFA? Or was it a
private server?

**Comment by krzycho1024** [comment]
Official FFA Europe. It was middle of the night(look at screens) so there wasn't many players and it was easy to kill all and make server empty.
After killing other players I was eating mass/viruses, then when i had ~16-18k(it's hard to get more) I threw mass in corner till I has ~1k. I made it few times(like 3), then again to get as much mass as possible. I waited to recombine to 1 cell and then tried to eat all my mass from corner. The cell was divided into two with equal mass and with one of cells I eat rest of it.
At that time I wasn't playing on private servers- I was able to join one server with friends at work. When this feature was disabled I started interesting Ogar. When screens where made I didn't even tried connect any server- I was playing alone, and it was just random FFA server.

**Comment by Ephemerality** [comment]
Alrighty, we'll add it and see what happens.

**Pull request merged**
